---
abstract: 'DBI based session engine for Dancer'
author:
  - 'James Aitken <jaitken@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300029, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Session-DBI
requires:
  DBI: 0
  Dancer: 0
  Try::Tiny: 0.01
  parent: 0.222
  perl: 5.010001
resources:
  bugtracker: https://github.com/LoonyPandora/Dancer-Session-DBI/issues
  homepage: https://github.com/LoonyPandora/Dancer-Session-DBI
  repository: https://github.com/LoonyPandora/Dancer-Session-DBI.git
version: 1.1.0
