---
abstract: 'DBI based session engine for Dancer'
author:
  - 'James Aitken <jaitken@cpan.org>'
build_requires:
  Test::More: 0.63
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300037, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Session-DBI
requires:
  DBI: 0
  Dancer: 0
  Try::Tiny: 0.01
  parent: 0.215
  perl: v5.8.8
resources:
  bugtracker: https://github.com/LoonyPandora/Dancer-Session-DBI/issues
  homepage: https://github.com/LoonyPandora/Dancer-Session-DBI
  repository: https://github.com/LoonyPandora/Dancer-Session-DBI.git
version: 1.2.1
